#!/bin/sh

# script by Eric Stein http://cons.truct.org

# This program is free software. It comes without any warranty, to
# the extent permitted by applicable law. You can redistribute it
# and/or modify it under the terms of the Do What The Fuck You Want
# To Public License, Version 2, as published by Sam Hocevar. See
# http://sam.zoy.org/wtfpl/COPYING for more details. 

if [ ! -f "$4" ]
then
	echo "no such file: $4"
	exit 1
fi

BNAME=`basename "$4"`
if [ $? -gt 0 ]
then
	echo "no basename."
	exit 1
fi
LNAME=`realpath "$4"`
if [ $? -gt 0 ]
then
	echo "no realpath."
	exit 1
fi

echo $BNAME | egrep -q '\.txt$'
if [ $? -gt 0 ]
then
	echo "not a .txt, aborting."
	exit 1
fi

PDFNAME=`echo ${BNAME}|sed -e 's/^\(.*\)\.txt$/\1/g'`.pdf

TDIR=`mktemp -d`
if [ $? -gt 0 ]
then
	echo "Failed to create temp dir."
	clean_up
fi

clean() {
	cd
	if [ -d $TDIR ]
	then
		rm -rf $TDIR
	fi
}

clean_up() {
	clean
	exit 1
}

cd $TDIR
if [ $? -gt 0 ]
then
	echo "Couldn't cd to temp dir."
	clean_up
fi

tp "$LNAME" "$PDFNAME"
if [ $? -gt 0 ]
then
	echo "Failed to convert to PDF."
	clean_up
fi

smtpfile "$PDFNAME" $1 $2 $3 $SMTPSERVER
if [ $? -eq 0 ]
then
	echo "Delivered $PDFNAME."
fi
clean
